version: "3.6"

services:
  fastapi_db:
    image: mysql:5.7
    container_name: fastapi_mysql
    environment:
      MYSQL_PASSWORD: 11111111
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: fastapi_test_db
    volumes:
      - ./db/mysql/mysql_data:/var/lib/mysql
    ports:
      - '8000:3308'
    networks:
      - fastapi-network

  phpmyadmin:
    depends_on:
      - fastapi_db
    image: phpmyadmin/phpmyadmin
    container_name: fastapi_php
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: fastapi_db
    networks:
      - fastapi-network

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_py
    image: fastapi_py
    env_file: dev.env
    ports:
      - '8023:8000'
    tty: true
    volumes:
      - ./src:/app:rw
    networks:
      - fastapi-network

networks:
  fastapi-network:
    external:
     name: fastapi-network







